### ISSUE TITLE
Invalid Date in Firefox

### ISSUE THREAD

**Issue by cykl** [wagenaartje/stocks.js#12]
`date` is always set to `Invalid Date` in Firefox. 

Issue is that `newSample['date'] = new Date(key + ' EDT');` isn't proper ES[56]. Date's ctor expects a RFC 2822 or ISO8601 `dateString` but `YYYY-MM-DD EDT` isn't. Chrome seems more lenient than FF. 

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by wagenaartje** [comment]
Thanks for the tip. The new way I'm implementing is as follows:

```js
newSample['date'] = new Date(Date.parse(key) + (240 - new Date().getTimezoneOffset()) * 60000);
```

I tested it on FireFox and it seems to work, let me know if it still doesn't work as expected.

**Comment by cykl** [comment]
It works like a charm. Thanks.
