### ISSUE TITLE
XMLHttpRequest require to use node target in webpack

### ISSUE THREAD

**Issue by kresli** [wagenaartje/stocks.js#4]
I need to add `target: 'node'` to my webpack config otherwise I've got this error

```
ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'fs'
```

```
ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Can't resolve 'child_process'
```

I would suggest to use https://www.npmjs.com/package/whatwg-fetch. I can create a pull request

**Comment by wagenaartje** [comment]
Hmm. I'm not sure why this is happening. Are you sure using the linked library would fix this? What node version are you using?

**Comment by kresli** [comment]
```
node -v
v8.1.3
```
I created a sample repo. https://github.com/kresli/stocks-js-test. You can test it with `npm run build`

**Comment by wagenaartje** [comment]
Yep. Managed to reproduce it. I'll do some tests.

**Comment by wagenaartje** [comment]
I'm quite embarassed to say I never knew `fetch` existed. If you're sure that this doesn't create any problems (and if you're sure it fixes the current one), please do switch from XMLHttpRequest to the listed library.

It seems to work like a charm:

```js
fetch('https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MSFT&interval=1min&apikey=demo')
  .then(function (response) {
    return response.json()
  }).then(function (body) {
    console.log(body)
  });
```

**Comment by wagenaartje** [comment]
I made a version with `fetch`. I tested it, and it seems to have fixed the problem :+1:

**Comment by parvezk** [comment]
Follow this approach, it will solve the problem:
https://github.com/webpack/webpack-dev-server/issues/66
