### ISSUE TITLE
stocks.js as name is not recommended 

### ISSUE THREAD

**Issue by kresli** [wagenaartje/stocks.js#7]
Please see
https://docs.npmjs.com/files/package.json#description
under `Some tips:`

**Comment by wagenaartje** [comment]
Similar names without `.js` are already taken, and typing just `stocks` on Github will show a bunch of other repositories. I named it `stocks.js` as I saw other projects with a similar name: Brain.js, angular.js, three.js, reveal.js, impress.js, turbo.js, parallel.js and to continue.

If `stocks` wasn't taken on npm, I would have published it under `stocks` on npm and still call it `stocks.js` - unfortunately it was taken.

_However_, if you come up with some really good name: please share it :smile:
